# Generated by Django 5.1.6 on 2025-03-07 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_product_size_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
