# Generated by Django 5.1.6 on 2025-02-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_image_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_size',
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
