# Generated by Django 5.1.6 on 2025-03-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_category_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True),  
            preserve_default=False,
        ),
    ]
