# Generated by Django 5.1.6 on 2025-03-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_category_remove_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
