# Generated by Django 5.1.6 on 2025-03-10 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_delete_category_remove_orderitem_cart_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
