# Generated by Django 5.1.6 on 2025-03-01 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.order'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reset_password_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
