# Generated by Django 5.1.6 on 2025-03-01 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_payment_order_id_payment_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='mode_of_payment',
        ),
    ]
